---
title: "Lecture 8"
format: revealjs
editor: visual
---

## Democracy

Democracy's defining characteristic is *contestability* which requires certain features of elections and certain protections for political minorities

Wide variety *institutions* - political rules of the game - provide contestability

Distinguish types by the location of executive power: Presidential, parliamentary, and semi-presidential - description and definition (Today)

Study effects of different types (Wednesday)

## Questions about Presidential, Parliamentary and Semi-parliamentary labels

Descriptive questions (definition):

                + What do the distinctions capture?

                +What do they miss?

Scientific questions:

                + What differences can we observe in choice of system?
                
                + What differences can we observe in results of the systems?

                + What type produces the most stable democracy?

                + What type is most responsive to popular sentiment?

                + What type best protects minority rights?
                

## Presidentialism and Parliamentarism

+ Not defined by:

                + Presence of a parliament - Presidential systems have legislatures and some are called parliaments
                + Presence of a President - Parliamentary systems may have a head of state called a President
                
+ Defined by the source and accountability of executive power

                + In a parliamentary system, executive power is a parliamentary power
                + Parliamentary systems are characterized by a lack of separation of powers
                + In a presidential system, executive power rests in an executive (a President) elected by the people
                + Presidential systems are characterized by a separation of powers with a strong, independent executive
                
## Presidentialism and Parliamentarism: Examples    

Presidential systems:

                + The United States
                + Mexico
                + Brazil
                
Parliamentary systems:

                + The United Kingdom
                + Italy
                + Japan
                + The Netherlands
                
Semi-parliamentary/Semi-Presidential systems:

                + Portugal
                + France
                + Russia
                + Taiwan


## Parliamentarism: Definitions & Characteristics

+ Prime minister/premier: head of government
+ PM and cabinet members of parliament
+ PM and cabinet hold executive power
+ PM answerable to parliament (no confidence votes)
+ President or other head of state is largely ceremonial
+ President may have duties around calling elections
+ Characterized by lack of separation of powers


## Presidentialism: Definitions & Characteristics

+ President: directly or indirectly elected by people
+ President: not subject to parliament [^1]
+ President holds executive power
+ Parliament holds legislative power
+ Characterized by separation of powers

   [^1]: other than exceptional circumstances such as criminal acts. Example: Impeachment for high crimes and misdemeanors in US system.

## Semi-presidentialism

+ Head of state: elected
+ Head of state: more than ceremonial power
+ Prime minister: answers to parliament
+ Prime minister: has executive power 
+ Split executive power


## 