---
title: "Final Exam Review"
format: revealjs
editor: visual
---

## Grading issues process

+ The exit survey is the last available extra credit. 
+ Minor issues 
                
                + Missing grade, missing quiz exemption, missing peer feedback*, etc.
                + Check Blackboard first
                + Email subject: "POLS 3311 - Minor grade issue" 
                + No email attachments
                + Monday to Friday next week only (December 5 to 9)
                + Allow 1 business day for acknowledgment
                + If you have never emailed me before, please use your @cougarnet.uh.edu email address if at all possible

+ Major issues

                + Regrades, etc. 
                + Do not email
                + Put request in writing on paper 
                + Include the original graded assignment/test in question (make a copy first, if you desire)
                + Place in my mailbox in the Political Science office between Nov 30 and Nov 5 at 4:00 PM

## Questions

1.  50-60 multiple choice, true-false, fill-in-the blank, multiple answer
2. 1 minute per question to complete
3. Possible additional bonus questions (no time adjustment)
4. No written questions.
5. Fill in the blank will need specific answers covered multiple times in lecture (wil be reviewed for typos only)
6. Total possible will be the lower of 50 or the top score



## Format

+ Online
+ In Blackboard
+ 1 hour to complete
+ Any day/time from Friday, December 9 at 2 PM to Wednesday, December 14 at 5 PM
+ Any web browser

## Rules 

+ Open note
+ Open resources, but

**Remember**:

+ Answers will be based on course materials and comparative politics, so answers from other fields may be **wrong**
+ Long searches will probably hurt you in time management


## Topics (1)

+ Basics

                + What is politics? What is the state? What is comparative politics?
                + Science - Scientific Method
                + Comparative Method
                + Collective Choice
                + Types of government: Democracy vs Dictatorship
                
+ Democracy

                + Forms of Democratic Government: Presidential vs Parliamentary Systems
                + Electoral Systems: Majoritarian vs Proportional Representation (PR)
                + Party Systems
                + Incentives and disincentives
                + Institutions - formal and informal
                
## Topics (2)

Know key distinctions - how do they differ?

                 + Political Science vs Political Theory (Postive/Empirical versus Normative/Philosophy)
                 + Types of goods - rival vs nonrival, excludable vs non-excludable
                 + Proportional Representation vs Majoritarian
                 + Closed list vs Open list
                 + Democracy vs Non-democracy
                 + Presidential vs Parliamentary

## Topics (3)

+ Types of dictatorships

                + degree
                + institutions
                + motivations
                + traditional terms
                
+ Selectorate theory (basic)
+ Nondemocratic institutions

                + formal
                + informal
                + civil society organizations

## Topics (4)

+ Economic Development and Democratization
+ Question: correlation of wealth and democracy
+ Answers:

                + Democracy causes growth
                + Growth causes democracy
                + Third thing causes both
                
Theories and explanations

                + Modernization theory
                + Stationary bandits
                + Investment security
                + Selectorate theory
                + Conditional modernization
                + Cultural 
                + Geographic / Resources
                + Evolutionary process
                
## Topics (5)

+ Theory development
+ Autocracy promotion (know what it is)
+ Democratic backsliding

                + What is it?
                + Norris - where is erosion of norms most prevalent
                + Hyde - elections since 2010
                + Norris - two big threats
                
                
## Topics (6)

+ International
+ Democratic Peace

                + What does it say?
                + What does it not say?
                + Alternative explanations - liberal, capitalist, industrialist peace
                + role of trade
                + role of democracy (contestation, elections, norms)
                
+ Trade and Globalization

                + Globalization - liberalization of international trade and finance
                + Issues are complex
                + Theoretical background - absolute advantage, comparative advantage, New Trade Theory
                + The case for trade/globalization
                + Winners and losers
                + Issues: Conflict, distributional issues, environmental issues


## How to study and test

1. Review midterm answers
2. Review quizzes
3.  Review lecture materials

                + Bold, italic, and capitalized words reflect major concepts 
                + Repeated items are important
                + Know the broad categories basic definitions 
                + Recognize key terms and other key terms they relate to
                + General good test taking strategies for this type of test
                + I suggest having one or two pages of really good notes based on lectures to refer to
                + Key words to consider "always" or "never" vs "often" or "rarely". 
                + Remember systems are complex but we use simple models to study one effect at a time



