---
title: "Readings week of November 7"
format: html
editor: visual
---

## Required

Hyde SD. Democracy's backsliding in the international environment. Science. 2020 Sep 4;369(6508):1192-1196. doi: 10.1126/science.abb2434. PMID: 32883862.

All (4 pages). Short piece from *Science* on the current environment of democratic backsliding. 

Norris, Pippa. "Is Western Democracy Backsliding? Diagnosing the Risks." HKS Faculty Research Working Paper Series RWP17-012, March 2017.

Read all. Excellent background on democratic backsliding from one of the top comparative politics scholars working on issues of the health of democratic institutions from the Harvard Kennedy School of Government.

## Recommended

Bryant, & Chou, M. (2016). China's New Silk Road: Autocracy Promotion in the New Asian Order? Democratic Theory (Brooklyn (New York, N.Y.)), 3(2), 114--124. https://doi.org/10.3167/dt.2016.030207

Introduction. Good material on autocracy promotion in the case of China's New Silk Road initiative also known as the Belt and Road initiative.

Yakouchyk. (2019). Beyond Autocracy Promotion: A Review. Political Studies Review, 17(2), 147--160. https://doi.org/10.1177/1478929918774976

For anyone wishing to address autocracy promotion in a paper, this should be the starting point.

Akyuz, Kadir, and Steve Hess. "Turkey Looks East: International Leverage and Democratic Backsliding in a Hybrid Regime." Mediterranean Quarterly 29, no. 2 (2018): 1-26. muse.jhu.edu/article/696568.

Pages 1 and 2 for global background on democratic backsliding.

Rakner, L. (2021), Don't Touch My Constitution! Civil Society Resistance to Democratic Backsliding in Africa´s Pluralist Regimes. Glob Policy, 12: 95-105. https://doi.org/10.1111/1758-5899.12991

Abstract/Introduction/Conclusion - review tables and figures. A comparative study on democratic backsliding in Zambia and Malawi. Explores the importance of *contestation* and *civil society* in protecting democracy from backsliding. Good example of two country study.

VonDoepp, P. (2020). Resisting Democratic Backsliding: Malawi's Experience in Comparative Perspective. African Studies Review, 63(4), 858-882. doi:10.1017/asr.2019.62

Abstract/Introduction/Conclusion - review tables and figures. A second comparative study on democratic backsliding in Zambia and Malawi, also focusing on civil society resistance to backsliding.

Corrales, Javier. "Democratic Backsliding through Electoral Irregularities: The Case of Venezuela." European Review of Latin American and Caribbean Studies / Revista Europea de Estudios Latinoamericanos y Del Caribe, no. 109 (2020): 41--65. https://www.jstor.org/stable/26936902.

Abstract/Introduction/Three Routes to Democratic Backsliding - review figures and graphs. An important piece on the preconditions that led to democratic backsliding in the Chavez regime in Venezuela.

## Background/potential paper sources

Gibler, Douglas M., and Kirk A. Randazzo. "Testing the Effects of Independent Judiciaries on the Likelihood of Democratic Backsliding." American Journal of Political Science 55, no. 3 (2011): 696--709. http://www.jstor.org/stable/23024945.

A large-n cross national comparative study of the effects of independent judicial branches on democratic backsliding. A good example of a large-n study.

Meyerrose, A. M. (2020). The Unintended Consequences of Democracy Promotion: International Organizations and Democratic Backsliding. Comparative Political Studies, 53(10--11), 1547--1581. https://doi.org/10.1177/0010414019897689

Examines the unintended effect of democracy promotion leading to democratic backsliding, the opposite of its intention.

Akyuz, Kadir, and Steve Hess. "Turkey Looks East: International Leverage and Democratic Backsliding in a Hybrid Regime." Mediterranean Quarterly 29, no. 2 (2018): 1-26. muse.jhu.edu/article/696568.

Examines the case of Turkey as a hybrid regime undergoing democratic backsliding (also known as authoritarian deepening). Good general background material in pages 1 through 6 on democratic backsliding globally.
