---
title: "Lecture 17"
format: revealjs
editor: visual
---

## Quiz Answers

                1. Selectorate theory is concerned with the relative size of the selectorate and the ________ _______? (Two words, only one right answer) WINNING COALITION
                2. The main motivation of nondemocratic leaders (and democratic leaders as well), is ________. (This is fill in the blank - a single word or two will work.) POWER
                3. Jessica Weeks typology of dictators is based on two dimensions, both commonly used in analyzing leader behavior. One is the leader's domestic audience. The other is ___________ _________. (One or two words.)    EXECUTIVE CONSTRAINTS (CONSTRAINT(S) is the key word)         
                4. An important modern version of oligarchy is _______ ______ rule. SINGLE PARTY
                5. Geddes, Frantz, and Wright an important means of classifying autocracies. Under her system, a regime in which the "control over policy, leadership selection, and the military apparatus" is in the hands of the military as an institution is a ___________ dictatorship. If the control is in the hands of a royal family the dictatorship is a ________. (Geddes et al, p.318, 2014)  MILITARY,MONARCHY or HEREDITARY MONARCHY

## Why are economic development and political development correlated?

Richer[^1] countries are more likely to be democratic.

[^1]: Defining rich as higher total national income (GDP) or as higher median income

Democratic countries are more likely to be rich.

Why?

## Why are economic development and political development correlated?

General Possibilities:

Democracy leads to economic development.

Economic development leads to democratization.

Something else leads to both.

## Why might democracy cause economic growth?

## Why might democracy cause economic growth?

1. Security for investment^[It is important to understand that investment doesn't just include business investment. Personal investment in education and skill building are affected by the same incentives and disincentives.]
        
        1. Constraining the executive creates security against the state
        2.  Political stability - democracy reduces civil strife
        
2.  Selectorate theory
3.  Stationary bandit incentives

## Selectorate Theory

1. Democratic leaders satisfy W with public goods
2. Reduce costs of private production - improvements in public goods 
2. Improves investment security - security as public good 
3. Both - shifting from redistribution of private goods from S to W, to general investment in public goods 

## Stationary Bandit incentives

"democratic political leaders are just as self-interested as the stationary bandit and will use any expedient to obtain majority support"^[(Olson 1993, p.570)]

Making the electorate better off improves re-election chances^[ibid.]

1. Leaders have incentive to invest in public goods to ensure future growth
2. Protection creates incentives for citizens to invest more 

## Why might economic growth lead to democratization?

## Why might economic growth lead to democratization?

Modernization theory: economic security allows people to consider nonmaterial desires

-   Similar to Maslow's hierarchy of needs from psychology

                  1. Physical needs
                  2. Security needs

                  3m. Maslow: Love and belonging, Self-esteem, self-actualization
                  3p. Politics: Civil society belonging, participation, self-determination, freedom

    ======= 3. Other needs: Freedom, self-determination, self-government

-   Political participation has costs

                  + Dictator's Handbook rules

## What other factors might contribute to both?

Next week!
