---
title: "Glossary: POLS 3311"
format: html
editor: visual
---

## Cause and effect

In cause and effect, the effect is the result that would not happen without the cause, everything else being equal.

## Collective action

Joint action. One or more individuals acting together to achieve a goal.

## Collective action problems

A situation where cooperation would be the best solution for all parties, but incentives exist which discourage cooperation between individuals.

## Comparative Methhod

The comparative method involves the study of a variable's causes or effects across two or more similar political entities, or the same entity at two or more points in time. Countries are compared to countries, states/provinces to states/provinces, cities to cities.

The comparative method is one of four approaches - experimental, statistical, comparative, and case study

## Constraints on the executive

Constraints are limits. Constraints on the executive are institutional limitations on executive action or power. That is, these are limits on the head of government embedded in the rules of the particular political system. These may be formal institutional constraints, such as legislative or judicial override of executive actions. They may be informal constraints, such as observance of a tradition of serving a limited number of terms. Enforcement may be formal and legal, or informal through tradition, norms, or civil society.

## Dependent Variable

In science the dependent variable is the outcome, result, or effect.

## Externality

A side effect of a transaction that affects third parties and whose cost or benefit is not included in the transaction, so the full social value of the transaction is not included in the price. Negative example: live music on a bar patio causes noise in the neighborhood. Positive example: A beekeeper keeps bees for honey and they pollinate plants on surrounding farms.

## Falsifiable

A falsifiable hypothesis is one which is sufficiently measurable and precisely defined that it can be tested and potentially disproven.

Testing falsifiable hypotheses is core to the scientific method.

Falsifiabilty was described by Karl Popper (1902-1994) as part of critical rationalism

## Hypothesis

plural - hypotheses

A testable proposition to determine if a theory is true or false. If the hypothesis is disproven, the theory is incorrect as written. If the hypothesis is not disproven, it and the theory are *confirmed as approximately true* given the current data.

## Incentive

Things that motivate or encourage/discourage behavior. Incentives may be positive or negative.

## Independent Variable

In science, the independent variable is the potential cause, the input, whose value is independent of other variables in the study.

## Method of Difference

Starts with states that differ in the result (dependent variable/outcome) and have many similarities

From John Stuart Mill (1806-1873)

## Method of Similarity

Starts with states with the same result (dependent variable/outcome) and many differences

From John Stuart Mill (1806-1873)

## Politics

Simplest: behavior involving state power

Clark: "...the subset of human behavior that involves the use of power"

Ostrom: behavior involving collective action

## Power

*For purposes of the study of politics*, power is the coercive use of physical force.

## Rational

A person or group of people (including a state) is considered rational if it behaves to maximize its utility given its beliefs.

In this context, the beliefs refer specifically to the beliefs about the likelihood of outcomes based on actions.

Utility refers to worth, value, pleasure, or happiness for the person or group. It is subjective.

## Scientific Method

The study of causes and effects based on empirical proof using the scientific method. Core elements of science are skepticism and falsifiability.

                + Define a research question
                + Make predictions - hypotheses
                + Gather data
                + Analyze the data to test the hypothesis
                + Draw conclusions

## State

The entity that engages in the organized, coercive use of physical force commonly accepted as legitimate.

## Utility

Utility refers to the subjective worth, value, pleasure, or happiness derived from an action or object.

## Variable

In science a variable is any factor that can vary in amount or type.
