---
title: "Lecture 12"
format: revealjs
editor: visual
---

## Quiz (worth 5 points)

                1. What is the main defining characteristic of democracy? (1 word) c_______
                2. What determines if a country (or other political entity) is a Presidential or Parliamentary system? (best answer is four words)
                3. First Past the Post is an example of what type of electoral system?
                4. In what type of proportional representation does the party choose who fills the seats that are won based on their pre-election ranking on a party list?
                5. In what type of proportional representation are the seats filled based on the voters preferred candidates from the party list?
                6. What is the minimum number of viable parties required for a country to be considered democratic?
                

## Recap: Important for today

Democracy - contestation

                - competition
                - chance of loss
                - multiple competitors

Another way of thinking about contestation: Differing viewpoints are able to *contest* the election and be represented.

Presidential vs Parliamentary

                + Location of executive power
                + In parliamentary systm, the legislature chooses the head of government from its own members
                

## Recap

Majoritarian vs Proportional Representation

**Choice of electoral system influences the selection of head of government in parliamentary system**

Majoritarian

                + Single member districts
                + Majority/plurality winner
                + Voters choose specific candidates
                + FPTP is a common, simple example

Proportional Representation

                + Multiple member districts (Magnitude 2+)
                + Seats awarded proportional to party vote
                + Closed list - vote by party, party chooses specific members
                + Open list - vote by party, voters choose specific members
                
## Centrist vs Extremist

**In a democratic context** - nondemocratic actions (kidnapping, political prisoners, terrorism, etc.) are not considered. They make the election flawed in any case.
 
                + "...it should be emphasized that the notions of "center" and "extreme" are defined relative to the particular electorate in question, rather than to any absolute or broader standard. Thus, the extremism of a particular candidate is determined not by describing the content of his ideology (Marxist, liberal, etc.), but rather by describing what percentage of the electorate holds views further to the left (or further to the right). In an electorate in which 50% of the voters are to the left of Marx, and 50% to the right, Marx would be considered centrist." (Cox 1990)
                + In 1850 in the United States House of Representatives, the Fugitive Slave Act passed by 48-7 with 14 abstentions (10% opposed). Opposing the Fugitive Slave Act in 1850 was relatively extremist.  
                

## What happens if?

In parliamentary systems, the Parliament chooses a Prime Minister and Cabinet.

What happens in a PR system if no party gets 50% of the seats in Parliament?

## Apportionment of votes

-   May be a minimum vote threshhold
-   Different methods benefit different size parties
-   largest remainder method - example, Hare quota method

Exceeding $\frac{total votes}{total seats}$ guarantees a seat

-   Divisor methods - example, d'Hondt method

$quot = \frac{V}{s + 1}$

V = total votes received by party; s = number of seats party received so far; Largest quotient gets the next seat

## Apportionment

Election outcome

+ Orange 221 votes 
+ Green  123 votes 
+ Yellow 97 votes 

+ Total Votes: 441

+ Total seats: 25 


## Party systems
Which are democratic? Flawed democracy? Nondemocratic?

-   Nonpartisan - party participation not allowed
-   One Party - opposition parties banned 
-   Dominant Party - opposition parties allowed but no prospect of success
-   Two Party - minor parties have no prospect of succcess
-   Multiple party - multiple parties allowed with some prospect of success



## Party systems

-   Nonpartisan (small countries, for specific offices, or nondemocratic)

-   One Party (non-democratic)

-   Dominant Party (flawed democracy or non-democratic)

-   Two Party

                  + de jure (likely flawed democracy or non-democratic)
                  + de facto - Duverger or similar natural outcome (may be democratic)

-   Multiple party (may be democratic)

## Discussion

1. General questions
2. Latin America and Britain articles
3. The US system 

## Discussion - General questions

1. Which system, majoritarian or PR, is most likely to lead to broad consensus building? Which is most likely to lead to stark partisan splits? Why?

2. Which system, majoritarian or PR, is most likely to have broadly accepted legitimacy among the population? 



## Discussion - Latin America and Britain articles

Latin America - Presidential system (has to be  majoritarian vote) but with proportional representation in the legislature?

- Linz idea about competing claims to democratic legitimacy vs Bello claims about consensus building?

Britain - First Past the Post System: Advantages and disadvantages?



## Discussion - The US System

3. The US system: Broad representation or centrism? Median voter theorem? 

        + Primary elections
        + Electoral college
        + Gerrymandering
