---
title: "Quiz - November 9"
format: html
editor: visual
---

## Your name _______________

1. In Susan Hyde's article "Democracy’s backsliding in the international environment," she had a figure which showed the total number of "elections with government harassment of opposition and/or media bias in favor of the incumbent" ________________ after 2010, while the total number of elections began to level off in the same period. (one word)

2. In recent years, according to Norris, "Millenials in Anglo-American democracies express ______________ support for democratic values, but this	is not a consistent	pattern	across Western democracies and post-industrial societies." (one word)

3. Norris says the data from Freedom  House shows that "the quality of institutions	protecting	political rights and civil liberties deteriorated" from 1972 to 2016, with the greatest erosion happening in:

                a. democracices
                b. hybrid regimes
                c. closed autocracies
                d. hereditary monarchies

4. Norris claims two related trends are the greatest threat to democracies. First are "sporadic and random terrorist attacks on domestic soil, which damage feelings of security," and second is "the rise of _____________________ forces, which feed upon these fears." (two words)

5. In laying out the conditions for democractic backsliding, Norris draws on Linz and Stepan's *Problems of Democratic Transition and Consolidation*, which proposes three conditions for democratic consolidation. Which of these is NOT one of the conditions:

                a. Cultural
                b. Economic
                c. Constitutional
                d. Behavioral

6. Which of the following is an example of an informal institution?

                a. Opposition press
                b. central banks
                c. the judiciary
                d. treaty commitments

7. In analyzing behavior, what is the primary motivation that overwhelmingly explains the behavior of politicians in both democratic and non-democratic societies?

                a. the greater good
                b. power
                c. nationalism
                d. ideology


