---
title: "Quiz November 14"
format: html
editor: visual
---

## Your Name \_\_\_\_\_\_\_\_\_\_\_\_\_

1.  Democratic peace theory claims that:

                a.  Democracies are more peaceful than nondemocracies.
                b.  Democracies are less likely to attack other countries than nondemocracies.
                c.  Democracies do not attack other democracies.
                d.  Democracies are less likely to be involved in interstate conflict, all else equal.


2.  Various scholars have claimed that the democratic peace is really a liberal peace, capitalist peace, industrialist peace, or contractualist peace. These notions argue that the relationship identified in the democratic peace is a \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ casued by democracies relationship with economic development and international trade.


3.  A major motivation, or at least public justification, for many American military engagements has been the promotion of democracy. This \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ the Democratic Peace.

                a.  disproves
                b.  proves
                c.  is not relevant to
                d.  is a requirement of

4. Since the end of the third wave of democratization, the number of elections has continued to increase, but the number of high quality elections has _________.

5. Compared to previous generations, Millenial support for democratic values is higher/lower. (Circle one)

6. The greatest erosion in civil liberties and constraining institutions in recent years has happened in what type of regime?

7. Give one example each of a formal and informal institution. 

8.  Several 19th century (1800s) engagements appear to have been between democracies, noteably the War of 1812. Name reasons these DO NOT conflict with the Democratic Peace. **Short phrases or single words only, no sentences or paragraphs.** Each reason is worth 1 point up to 3.
