---
title: "Quiz November 16"
format: html
editor: visual
---

## Your Name Here ___________

Democratic peace theory claims that:

                a. Democracies are more peaceful than nondemocracies.

                b. Democracies are less likely to attack other countries than nondemocracies.

                c. Democracies do not attack other democracies.

                d. Democracies are less likely to be involved in interstate conflict, all else equal.
                
2. There is **no evidence** that Democratic Peace is a consequence of market economies in democratic countries. True or false?

3. Several 19th century (1800s) engagements appear to have been between democracies, noteably the War of 1812. Name *one reason* these DO NOT conflict with the Democratic Peace. **No more than 3 words**

4. In an economic model with two goods, for two countries to each gain from trade, each must have an absolute advantage over the other in producing exactly one of the goods. True or false? 

5. Most theories of trade hold that society as a whole benefits from trade, all else equal, because of increases in *consumer surplus*. Do all members of society benefit equally? 

6. Globalization has been credited/blamed with (pick all that apply)

                a. Increasing the wealth of the poorest nations
                b. Increasing average or median income
                c. Increasing economic inequality 
                d. Decreasing absolute poverty
                e. Raising the living standards of the poorest members of society
                
7. Can all of the choices in 7 be true at the same time?