---
title: "Midterm: POLS 3311, Fall 2022"
format: html
editor: visual
---

## Section 1: Multiple Choice (4 points each)

1.  When something is proved by observation or experiment rather than pure logic or theory, it is said to be proved:

                 A - theoretically
                 B - thoroughly
                 C - empirically
                 D - absolutely

2.  The two types of proportional representation systems are majoritarian and:

                 A - open list
                 B - parliamentary
                 C - proportional representation
                 D - dictatorship

3.  What is the first step in the scientific method?

                 A - Analyze the data
                 B - Make predictions
                 C - Define a research question
                 D - Reach a conclusion

4.  The comparative method is one of four major methods of scientific or empirical political research. Which of the following is not one of the other three:

                 A - theoretical
                 B - statistical
                 C - Case study
                 D - Experimental

5.  Which of the following can potentially be answered by science **alone**:

                 A - right and wrong
                 B - good and bad
                 C - cause and effect
                 D - correct policy and incorrect policy

6.  Distinguishing democratic from nondemocratic (dictatorial/autocratic) regimes is based primarily on what concept?

                 A - Elections
                 B - Voting
                 C - Legal opposition parties
                 D - Contestation or contestability

7.  The core feature of contestability is the non-trivial (significant) chance that the governing party will:

                 A - Allow opposition in the election
                 B - Allow elections
                 C - Lose the election
                 D - Appoint opposition members to the government

8.  Other features necessary for true contestability include irreversibility, repeatability, and:

                 A - majority rule
                 B - protection of minority rights
                 C - international observers
                 D - direct democracy

9.  In checking for real contestability, four rules help us. Which of these is not a rule we use to test for democracy?

                 A - There must be more than one party
                 B - The chief executive must be elected directly or indirectly
                 C - Judges must be elected
                 D - The legislature must be elected
                 E - There must have been an alternation in power

10. The type of proportional system where the voters choose the party, but have no influence over specific candidates is:

                A - Open list
                B - Democracy
                C - Closed list
                D - Primary

11. The form of democratic government where the executive power is located in the parliament (or other legislature) is:

                A - Presidential
                B - Ministerial
                C - Parliamentary
                D - Majoritarian

12. Country A has a democratic constitution which calls for an elected President who calls elections and attends diplomatic functions, a Prime Minister elected by the Parliament, and a Cabinet selected by the PM from the Parliament. This system is:

                A - Presidential
                B - Parliamentary
                C - Flawed democracy
                D - Proportional Representation

13. Country B has a democratic constitution with a President and a legislature called a Congress. This is all we know about this country. True or false: It must be a Presidential System, because it does not have a body called Parliament?

                A - True
                B - False

14. The major distinction between Parliamentary and Presidential Systems is:

               A - An official called a President
               B - A body called Parliament
               C - The location of executive power
               D - Judicial independence

15. A situation in which all parties would benefit from cooperation, but incentives exist which discourage individuals from cooperating is a:

               A - flawed incentive problem
               B - public choice problem
               C - collective action problem
               D - majority rules

16. The Method of \_\_\_\_\_\_ starts with states that differ in the result (dependent variable/outcome) and have many similarities, and looks for the other major difference as the cause.

               A - Comparative method
               B - Case study
               C - Method of Difference
               D - Method of Similarity

17. The entity which has commonly accepted legitimacy for the coercive use of physical force is:

                A - the army
                B - the police
                C - the state
                D - the court system

18. True or false: All countries with multiple legal political parties are democracies?

                A - True
                B - False

19. A simple interpretation of Duverger's Law is that First Past the Post election rules result in this:

                A - flawed democracy
                B - democratic backsliding
                C - two party systems
                D - proportional representation

20. The Prisoner's Dilemma is an example of a \_\_\_\_\_\_\_\_ action problem that may be solved by enforcement or repeated interaction.

               A - coercive
               B - police
               C - collective
               D - dictatorship
               
{{< pagebreak >}}

## Section 2: Short answer (10 points each)

**Pick 2 questions to answer. Answering a third does not get any additional credit.**

**Answers should be one to four sentences. They should usually fit in the space provided, but you may also use the back of the page.**

21. Briefly describe what happens if a piece of legislation proposed by the head of government fails to pass in a Parliamentary System and in a Presidential System.

22. <p style="margin-bottom:10cm;">Briefly explain why failing to protect minority rights makes a country undemocratic being sure to mention the specific requirement of democratic elections that is undermined by not protecting minority rights.</p>



23. <p style="margin-bottom:10cm;">Why can science alone not decide the answer policy questions?</p>


<p style="margin-bottom:10cm;">.</p>

## Section 3: Bonus (10 points each)

**Use the back of the page and the attached blank page to do your work. Please make sure your final answer is obvious by underlining, etc.**

Bonus 1. Military Dispute Equilibrium:

Country A and Country B have a dispute over a resource rich area on their border. Country A currently controls it and Country B has demanded that Country A give it up. If war occurs, the country which attacks first will have a major advantage. The value of the resource and both the human and material costs of war have been computed in financial terms for both countries using standard methods. If war occurs, Country A will suffer a loss of 200 billion if it atacks first and 500 billion if it attacks second. If war occurs, Country B will suffer a loss of 100 billion if it attacks first and 300 billion if it attacks second. If war does not occur, neither country suffers a loss. What is the equilibrium outcome? (Use the Prisoner's Dilemma as a guide to your thinking.)

<p style="margin-bottom:10cm;"></p>


Bonus 2. Allocation of seats in PR system

You have the following election outcome in a Proportional Representation system. How will the seats be allocated using a Hare quota method? Using the d'Hondt divisor method?

Total seats: 10

Total votes: 125 million

Green Party: 25 million

Red Party: 35 million

Orange Party: 55 million

Purple Party: 10 million

<p style="margin-bottom:10cm;"></p>
