---
title: "Corruption and Repression"
format: revealjs
editor: visual
---

## Recap on Globalization, Trade, Conflict - and everything else

1.  These are complex systems
2.  Seemingly contradictory things can go hand in hand
3.  Science can help us measure trade-offs
4.  Valid unbiased science and normative (idealistic) ideas can make good policy but...
5.  Ideological talking points that don't recognize 1 to 3 bias scientific results.

## Full process

1 - ideals give us questions

                + What causes mass violence?
                + What causes war?
                + How can poverty be reduced?

2 - apply the unbiased Scientific Method to find answers
3 - take those answers and our ideals to make policy

## Globalization, Trade, Conflict

Example:

Globalization (trade and financial liberalization) has been blamed or praised for:

                1. Decreasing absolute poverty - G
                2. Increasing inequality - B
                3. Improving median incomes - G
                4. Causing unemployment in manufacturing communities - B
                5. Raising living standards of the poorest people - G
                6. Increasing total employment/productivity for all trading partners - G

-   All of these *can* be true
-   All of these *are* empirically valid statements of the real world
-   None of these address other issues like conflict, the environment, or labor rights - potentially G or B

## Causes of Corruption and Repression

Focus:

-   Empirical study
-   Comparative study

in terms of topics from earlier in the semester:

-   institutions
-   incentives
-   selectorate theory

## Repression

-   Dictatorships
-   Democracies
-   Similarities?

## Repression - incentives and disincentives

-   incentives to repress
-   cost of repression

## Repression - incentives to repress

-   incentives to repress

## Repression - incentives to repress

-   incentives to repress - MAINTAIN POWER

                  + appease/protect/defend elites (W)
                  + prevent revolt (election loss in democracies)

## Repression - disincentives

-   cost of repression

## Repression - disincentives

-   cost of repression

                  + machinery of repression
                  + economic disruptions
                  + lost productivity from the repressed
                  + reputational costs (international)
                  + reputational costs (domestic) - potential backfire

## Democracy vs Dictatorship

-   Democracy vs dictatorship - what are the major differences?

## Democracy vs Dictatorship

-   Democracy vs dictatorship - differences

        + higher legal accountability of government - institutions
        + voting vs rioting (Ballard-Rosa)
        + Reputational costs 

## Within dictatorships

-   urban vs rural populations

                  + Urban populations easier to mobilize for rioting
                  + Urban populations more easily bought off with cheap food

-   differences in legal accountability

                  + power of legislature
                  + size and power of legal opposition
                  + power of civil society groups
                  + power and independence of judiciary

## Other issues

-   Preventive repression - harder to measure

## Corruption - definitions

-   Grand corruption
-   petty corruption

## Corruption - core issues

-   incentives toward corruption
-   accountability and responsibility

## Corruption - incentives

-   personal wealth

-   corrupt politics

                  + campaign costs
                  + buying votes
                  + other corrupt costs

## Corruption - accountability and responsibility

                + Legal (punitive)
                + Electoral
                + Party leadership
                

## Return quizzes and tests

+ Later this week

        + Exit survey (extra credit) on Blackboard
        + Grade questions - I'll discuss procedure on Wednesday. Do not email.

+ Wednesday

        + Final review
        + Evaluation
        
